Added "Sharding" section
McFranko/padlock-whitepaper pull request #7
Opened 2021-04-01 18:22 UTC by McFranko

Sharding is important for scaling and throughput, but could be a lot to promise for the first release. It could potentially be included as a later upgrade instead, or it could be included from the beginning.

2021-04-03 07:52 UTC, lindenstark commented on whitepaper.tex
> +chain. This becomes inefficient, as you have many copies of the same data, when
"you" implies reader is a blockchain

2021-04-03 07:53 UTC, lindenstark commented on whitepaper.tex
> +chain. This becomes inefficient, as you have many copies of the same data, when
Extra comma after "data"

2021-04-03 07:53 UTC, lindenstark commented on whitepaper.tex
> +merkle-proof of an entry, they will have to request it from one node of each
"merkle" should be capitalized

2021-04-03 07:54 UTC, lindenstark commented on whitepaper.tex
> +chains. This would result in an inefficient use of space. So, there is a
"in [an] inefficient" "an" is not needed

2021-04-03 07:57 UTC, lindenstark requested changes
There's a few grammatical mistakes.
Should we look for grammarly as a CI service, it'd make contributing scale a lot smoother?

2021-04-25 18:48 UTC, McFranko commented
Grammarly would only introduce spelling fixes, unless I pay for the premium version, which I'm not doing. I just didn't proof read this at all.

2021-04-25 18:50 UTC, McFranko commented
I don't think I will merge this anyways because since writing this I've realized the insecurity of a side-chain scaling solution. Everytime you add another chain you lower the hash power it takes to attack the network. (1 chain = 50%, 2 chains = 25%, 4 chains = 12.5%, etc).

2021-04-25 18:50 UTC, closed without merging